<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4. ¿Qué tan mal estamos? Estableciendo el Baseline y Métricas de Error – Arquitectura de suministros</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./cap-5-pronostico-ingenuo.html" rel="next">
<link href="./cap-3-abcxyz-dinamico.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6d7b16145a975a9b09f17f801b1fce15.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-1d61feaf5942a89f67c517e5b1b3c91a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-6d7b16145a975a9b09f17f801b1fce15.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./cap-1-auditoria.html">I: El Diagnóstico</a></li><li class="breadcrumb-item"><a href="./cap-4-metricas-error.html"><span class="chapter-title">4. ¿Qué tan mal estamos? Estableciendo el Baseline y Métricas de Error</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Arquitectura de suministros</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/nicobravo933-Planner/nicobravo933-Planner" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bienvenido</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">I: El Diagnóstico</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-1-auditoria.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1. Auditoría de Datos y Arquitectura de Red</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-2-espejo-realidad.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. El Espejo de la Realidad: Ventas vs.&nbsp;Demanda</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-3-abcxyz-dinamico.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3. Clasificando el Caos: Segmentación ABC/XYZ Dinámica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-4-metricas-error.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">4. ¿Qué tan mal estamos? Estableciendo el Baseline y Métricas de Error</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">II: Prediciendo el Futuro</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-5-pronostico-ingenuo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5. El Pronóstico Ingenuo: Modelos Simples y Benchmarking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-6-suavizamiento-exponencial.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6. Suavizando la Curva - La Inteligencia Estadística</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-7-arima-y-alternativas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7. Introducción: El Salto de la Suavización a la Correlación</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">III: El Arsenal del Científico de Datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-8-ingenieria-atributos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8. Introducción: El Cambio de Paradigma</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-9-bosque-decisiones.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9. El Bosque de las Decisiones - Random Forest y XGBoost</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-10-validacion-overfitting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10. El Desierto de los Datos</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">IV: La Ciencia del Stock</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-11-costos-inventario.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11. El Costo del Dinero y el Costo del Vacío</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-12-eoq-punto-reorden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12. El Paso del Pronóstico a la Orden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-13-stock-seguridad.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13. Bienvenidos al Mundo Estocástico</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-14-demandas-erraticas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14. Más allá de la Curva Normal</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">V: Simulaciones y Redes Complejas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-15-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15. El Laboratorio Virtual</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-16-efecto-domino-meio.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16. El Efecto Dominó</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-17-sim-opt-politica-perfecta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17. Optimizando bajo Presión</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">VI: El Factor Humano y la Ejecución</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-18-fva-valor-pronostico.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18. ¿Aportamos Valor? (Forecast Value Added)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-19-gestion-sesgos-humanos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19. El Algoritmo vs.&nbsp;el Ego</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cap-20-plan-maestro-sop.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20. El Plan Maestro</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notas-finales-estrategia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Notas y Recomendaciones Estratégicas</span></a>
  </div>
</li>
    </ul>
    </div>
<div class="quarto-sidebar-footer"><div class="sidebar-footer-item">
<p>Creado con <a href="https://quarto.org/">Quarto</a>.</p>
</div></div></nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#el-concepto-de-baseline-el-modelo-naive" id="toc-el-concepto-de-baseline-el-modelo-naive" class="nav-link active" data-scroll-target="#el-concepto-de-baseline-el-modelo-naive">4.1 El Concepto de Baseline: El Modelo “Naive”</a>
  <ul class="collapse">
  <li><a href="#el-s-naive-para-negocios-con-memoria-estacional" id="toc-el-s-naive-para-negocios-con-memoria-estacional" class="nav-link" data-scroll-target="#el-s-naive-para-negocios-con-memoria-estacional">4.1.1 El S-Naive: Para negocios con memoria estacional</a></li>
  </ul></li>
  <li><a href="#anatomía-del-error-magnitud-y-dirección" id="toc-anatomía-del-error-magnitud-y-dirección" class="nav-link" data-scroll-target="#anatomía-del-error-magnitud-y-dirección">4.2 Anatomía del Error: Magnitud y Dirección</a>
  <ul class="collapse">
  <li><a href="#magnitud-mae-vs.-rmse-lineal-o-exponencial" id="toc-magnitud-mae-vs.-rmse-lineal-o-exponencial" class="nav-link" data-scroll-target="#magnitud-mae-vs.-rmse-lineal-o-exponencial">4.2.1 Magnitud: MAE vs.&nbsp;RMSE (¿Lineal o Exponencial?)</a></li>
  <li><a href="#dirección-el-bias-sesgo-o-la-inclinación-al-error" id="toc-dirección-el-bias-sesgo-o-la-inclinación-al-error" class="nav-link" data-scroll-target="#dirección-el-bias-sesgo-o-la-inclinación-al-error">4.2.2 Dirección: El BIAS (Sesgo o la inclinación al error)</a></li>
  <li><a href="#matriz-de-decisión-qué-métrica-usar-y-cuándo" id="toc-matriz-de-decisión-qué-métrica-usar-y-cuándo" class="nav-link" data-scroll-target="#matriz-de-decisión-qué-métrica-usar-y-cuándo">4.2.3 Matriz de Decisión: ¿Qué métrica usar y cuándo?</a></li>
  </ul></li>
  <li><a href="#la-batalla-de-las-métricas-mae-bias-vs.-mape" id="toc-la-batalla-de-las-métricas-mae-bias-vs.-mape" class="nav-link" data-scroll-target="#la-batalla-de-las-métricas-mae-bias-vs.-mape">4.3 La Batalla de las Métricas: MAE + BIAS vs.&nbsp;MAPE</a>
  <ul class="collapse">
  <li><a href="#la-maldición-del-porcentaje-por-qué-el-mape-es-tramposo" id="toc-la-maldición-del-porcentaje-por-qué-el-mape-es-tramposo" class="nav-link" data-scroll-target="#la-maldición-del-porcentaje-por-qué-el-mape-es-tramposo">4.3.1 La Maldición del Porcentaje: ¿Por qué el MAPE es tramposo?</a></li>
  <li><a href="#el-experimento-del-espejismo-cómo-el-mape-destruye-tus-ventas" id="toc-el-experimento-del-espejismo-cómo-el-mape-destruye-tus-ventas" class="nav-link" data-scroll-target="#el-experimento-del-espejismo-cómo-el-mape-destruye-tus-ventas">4.3.2 El Experimento del Espejismo: Cómo el MAPE destruye tus ventas</a></li>
  <li><a href="#cuadro-comparativo-en-qué-bando-estás" id="toc-cuadro-comparativo-en-qué-bando-estás" class="nav-link" data-scroll-target="#cuadro-comparativo-en-qué-bando-estás">4.3.3 Cuadro Comparativo: ¿En qué bando estás?</a></li>
  <li><a href="#el-traductor-corporativo-a-quién-le-cuento-qué" id="toc-el-traductor-corporativo-a-quién-le-cuento-qué" class="nav-link" data-scroll-target="#el-traductor-corporativo-a-quién-le-cuento-qué">4.3.4 El “Traductor Corporativo”: ¿A quién le cuento qué?</a></li>
  </ul></li>
  <li><a href="#el-wape-weighted-mape-el-estándar-de-oro-para-gerencia" id="toc-el-wape-weighted-mape-el-estándar-de-oro-para-gerencia" class="nav-link" data-scroll-target="#el-wape-weighted-mape-el-estándar-de-oro-para-gerencia">4.4 El WAPE (Weighted MAPE): El Estándar de Oro para Gerencia</a>
  <ul class="collapse">
  <li><a href="#por-qué-es-el-puente-estratégico" id="toc-por-qué-es-el-puente-estratégico" class="nav-link" data-scroll-target="#por-qué-es-el-puente-estratégico">4.4.1 ¿Por qué es el puente estratégico?</a></li>
  <li><a href="#ejemplo-el-wape-en-acción-portafolio-a-vs.-b" id="toc-ejemplo-el-wape-en-acción-portafolio-a-vs.-b" class="nav-link" data-scroll-target="#ejemplo-el-wape-en-acción-portafolio-a-vs.-b">4.4.2 Ejemplo: El WAPE en acción (Portafolio A vs.&nbsp;B)</a></li>
  <li><a href="#fortalezas-y-debilidades-del-wape" id="toc-fortalezas-y-debilidades-del-wape" class="nav-link" data-scroll-target="#fortalezas-y-debilidades-del-wape">4.4.3 Fortalezas y Debilidades del WAPE</a></li>
  <li><a href="#resumen-de-selección-qué-métrica-elijo" id="toc-resumen-de-selección-qué-métrica-elijo" class="nav-link" data-scroll-target="#resumen-de-selección-qué-métrica-elijo">4.4.4 Resumen de Selección: ¿Qué métrica elijo?</a></li>
  </ul></li>
  <li><a href="#forecastability-el-límite-de-lo-posible" id="toc-forecastability-el-límite-de-lo-posible" class="nav-link" data-scroll-target="#forecastability-el-límite-de-lo-posible">4.5 Forecastability: El Límite de lo Posible</a>
  <ul class="collapse">
  <li><a href="#el-coeficiente-de-variación-cv-tu-detector-de-ruido" id="toc-el-coeficiente-de-variación-cv-tu-detector-de-ruido" class="nav-link" data-scroll-target="#el-coeficiente-de-variación-cv-tu-detector-de-ruido">4.5.1 El Coeficiente de Variación (CV): Tu detector de ruido</a></li>
  <li><a href="#la-matriz-de-predecibilidad" id="toc-la-matriz-de-predecibilidad" class="nav-link" data-scroll-target="#la-matriz-de-predecibilidad">4.5.2 La Matriz de Predecibilidad</a></li>
  <li><a href="#por-qué-importa-esto-el-impacto-en-el-stock-de-seguridad" id="toc-por-qué-importa-esto-el-impacto-en-el-stock-de-seguridad" class="nav-link" data-scroll-target="#por-qué-importa-esto-el-impacto-en-el-stock-de-seguridad">4.5.3 ¿Por qué importa esto? El impacto en el Stock de Seguridad</a></li>
  <li><a href="#el-escudo-del-planificador-concepto-de-forecast-goal" id="toc-el-escudo-del-planificador-concepto-de-forecast-goal" class="nav-link" data-scroll-target="#el-escudo-del-planificador-concepto-de-forecast-goal">4.5.4 El Escudo del Planificador (Concepto de “Forecast Goal”)</a></li>
  </ul></li>
  <li><a href="#tracking-signal-la-alarma-de-incendio-del-pronosticador" id="toc-tracking-signal-la-alarma-de-incendio-del-pronosticador" class="nav-link" data-scroll-target="#tracking-signal-la-alarma-de-incendio-del-pronosticador">4.6 Tracking Signal: La Alarma de Incendio del Pronosticador</a>
  <ul class="collapse">
  <li><a href="#cómo-se-calcula" id="toc-cómo-se-calcula" class="nav-link" data-scroll-target="#cómo-se-calcula">4.6.1 ¿Cómo se calcula?</a></li>
  <li><a href="#interpretación-los-límites-de-control" id="toc-interpretación-los-límites-de-control" class="nav-link" data-scroll-target="#interpretación-los-límites-de-control">4.6.2 Interpretación: Los Límites de Control</a></li>
  <li><a href="#el-tablero-de-control-visualizando-el-desvío" id="toc-el-tablero-de-control-visualizando-el-desvío" class="nav-link" data-scroll-target="#el-tablero-de-control-visualizando-el-desvío">4.6.3 El Tablero de Control: Visualizando el Desvío</a></li>
  <li><a href="#qué-hacer-cuando-suena-la-alarma" id="toc-qué-hacer-cuando-suena-la-alarma" class="nav-link" data-scroll-target="#qué-hacer-cuando-suena-la-alarma">4.6.4 ¿Qué hacer cuando suena la alarma?</a></li>
  </ul></li>
  <li><a href="#el-laboratorio-de-diagnóstico-implementación-en-r" id="toc-el-laboratorio-de-diagnóstico-implementación-en-r" class="nav-link" data-scroll-target="#el-laboratorio-de-diagnóstico-implementación-en-r">4.7 El Laboratorio de Diagnóstico: Implementación en R</a>
  <ul class="collapse">
  <li><a href="#el-script-de-auditoría-de-pronósticos" id="toc-el-script-de-auditoría-de-pronósticos" class="nav-link" data-scroll-target="#el-script-de-auditoría-de-pronósticos">4.7.1 El Script de Auditoría de Pronósticos</a></li>
  <li><a href="#gráfico-superior-auditoría-de-desempeño-el-qué" id="toc-gráfico-superior-auditoría-de-desempeño-el-qué" class="nav-link" data-scroll-target="#gráfico-superior-auditoría-de-desempeño-el-qué">1. Gráfico Superior: Auditoría de Desempeño (El “Qué”)</a></li>
  <li><a href="#gráfico-inferior-tracking-signal-el-por-qué" id="toc-gráfico-inferior-tracking-signal-el-por-qué" class="nav-link" data-scroll-target="#gráfico-inferior-tracking-signal-el-por-qué">2. Gráfico Inferior: Tracking Signal (El “Por qué”)</a></li>
  <li><a href="#diagnóstico-final-del-modelo-simulado" id="toc-diagnóstico-final-del-modelo-simulado" class="nav-link" data-scroll-target="#diagnóstico-final-del-modelo-simulado">3. Diagnóstico Final del Modelo Simulado</a></li>
  <li><a href="#resumen-para-gerencia" id="toc-resumen-para-gerencia" class="nav-link" data-scroll-target="#resumen-para-gerencia">Resumen para Gerencia:</a></li>
  </ul></li>
  <li><a href="#conclusión-del-espejo-retrovisor-al-parabrisas" id="toc-conclusión-del-espejo-retrovisor-al-parabrisas" class="nav-link" data-scroll-target="#conclusión-del-espejo-retrovisor-al-parabrisas">4.8 Conclusión: Del Espejo Retrovisor al Parabrisas</a>
  <ul class="collapse">
  <li><a href="#el-recuento-de-los-daños-y-de-las-ganancias" id="toc-el-recuento-de-los-daños-y-de-las-ganancias" class="nav-link" data-scroll-target="#el-recuento-de-los-daños-y-de-las-ganancias">4.8.1 El Recuento de los Daños (y de las Ganancias)</a></li>
  <li><a href="#la-transición-de-lo-descriptivo-a-lo-predictivo" id="toc-la-transición-de-lo-descriptivo-a-lo-predictivo" class="nav-link" data-scroll-target="#la-transición-de-lo-descriptivo-a-lo-predictivo">4.8.2 La Transición: De lo Descriptivo a lo Predictivo</a></li>
  <li><a href="#hoja-de-ruta-lo-que-viene-en-la-parte-ii" id="toc-hoja-de-ruta-lo-que-viene-en-la-parte-ii" class="nav-link" data-scroll-target="#hoja-de-ruta-lo-que-viene-en-la-parte-ii">4.8.3 Hoja de Ruta: Lo que viene en la Parte II</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/nicobravo933-Planner/nicobravo933-Planner/edit/main/cap-4-metricas-error.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/nicobravo933-Planner/nicobravo933-Planner/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./cap-1-auditoria.html">I: El Diagnóstico</a></li><li class="breadcrumb-item"><a href="./cap-4-metricas-error.html"><span class="chapter-title">4. ¿Qué tan mal estamos? Estableciendo el Baseline y Métricas de Error</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">4. ¿Qué tan mal estamos? Estableciendo el Baseline y Métricas de Error</span></h1>
</div>



<div class="quarto-title-meta column-body">

    
  
    
  </div>
  


</header>


<p>¡Bienvenido al momento de la verdad! Si llegaste hasta aquí, ya has construido los cimientos: tienes un mapa de tu red (Cap. 1), una demanda reconstruida que refleja la intención real de compra (Cap. 2) y tus productos clasificados por su importancia estratégica y su dificultad técnica (Cap. 3).</p>
<p>Ahora toca enfrentar la realidad. La pregunta que todo director financiero o de operaciones te hará no es si el modelo es “bonito” o si usaste una Red Neuronal, sino: <em>“¿Y qué tanto estamos fallando hoy?”</em>.</p>
<p>En Supply Chain, la honestidad brutal es tu mejor aliada. “Estamos más o menos” no es una métrica; es una opinión subjetiva que bloquea la mejora continua. Medir el error es, a menudo, un ejercicio de humildad corporativa que muchas empresas evitan para no evidenciar ineficiencias. Sin embargo, en este capítulo estableceremos el <strong>Baseline</strong> (tu punto cero de comparación) y aprenderemos a diseccionar el error en sus componentes de magnitud y dirección. Te voy avisando: si no eres capaz de medir el dolor financiero que causa tu error hoy, nunca podrás cuantificar el ahorro que traerán tus modelos avanzados mañana. Este es el “kilómetro cero” de tu transformación digital hacia una cadena inteligente.</p>
<hr>
<section id="el-concepto-de-baseline-el-modelo-naive" class="level2">
<h2 class="anchored" data-anchor-id="el-concepto-de-baseline-el-modelo-naive">4.1 El Concepto de Baseline: El Modelo “Naive”</h2>
<p>Antes de intentar predecir el futuro con modelos complejos, necesitamos un punto de referencia mínimo que represente el “esfuerzo cero”. En ciencia de datos aplicada, esto se llama el <strong>Modelo Base o Naive</strong>. Es el “rival a vencer” y la medida de tu propia ineficacia: si tu proceso actual no le gana a un modelo Naive, estás desperdiciando recursos humanos y tecnológicos.</p>
<p>La lógica del <strong>Pronóstico Ingenuo (Naive Forecast)</strong> es la persistencia absoluta: <em>“El mercado se comportará mañana exactamente igual que hoy”</em>.</p>
<p><span class="math display">\[
\large \hat{y}_{t+1} = y_t
\]</span></p>
<p><strong>Desglose de la fórmula y origen de datos:</strong></p>
<ul>
<li><span class="math inline">\(\large \hat{y}_{t+1}\)</span> (Pronóstico): Es la cantidad que estimamos que se demandará en el próximo periodo. Representa tu “apuesta” de inventario para el futuro inmediato.</li>
<li><span class="math inline">\(\large y_t\)</span> (Demanda Real): Es el valor de la <strong>Demanda Reconstruida</strong> (Unconstrained Demand) del Capítulo 2.</li>
<li><strong>Origen de los datos:</strong> Este valor debe venir de tu tabla de transacciones históricas filtradas. <strong>Crucial:</strong> Debe ser la demanda después de corregir quiebres de stock. Si usas la venta facturada (que es una venta restringida por tu propia falta de stock), tu baseline será artificialmente bajo y tus métricas de error parecerán mejores de lo que realmente son, ocultando el costo de oportunidad.</li>
</ul>
<section id="el-s-naive-para-negocios-con-memoria-estacional" class="level3">
<h3 class="anchored" data-anchor-id="el-s-naive-para-negocios-con-memoria-estacional">4.1.1 El S-Naive: Para negocios con memoria estacional</h3>
<p>Si tu negocio vende helados o calefactores, el Naive simple fallará. En ese caso, usamos el <strong>Seasonal Naive (S-Naive)</strong>: <em>“Diciembre de este año será igual a diciembre del año pasado”</em>.</p>
<p><span class="math display">\[
\large \hat{y}_{t+1} = y_{t+1-periodo}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>La Prueba de Fuego del Analista (FVA)
</div>
</div>
<div class="callout-body-container callout-body">
<p>El modelo Naive es tu “competidor silencioso”. En la Parte VI del libro utilizaremos este concepto para calcular el <strong>Forecast Value Added (FVA)</strong>. Si un equipo de 10 personas y un software de 100k USD no logran ser al menos un 10% mejores que un simple Naive, el proceso está “destruyendo valor”. Es preferible automatizar el Naive y dedicar a la gente a otra tarea.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="anatomía-del-error-magnitud-y-dirección" class="level2">
<h2 class="anchored" data-anchor-id="anatomía-del-error-magnitud-y-dirección">4.2 Anatomía del Error: Magnitud y Dirección</h2>
<p>Un error de 100 unidades no impacta igual en el balance contable si sobraron (exceso) que si faltaron (quiebre). Para un profesional de Supply Chain, el error es un vector con dos dimensiones críticas: la <strong>magnitud</strong> (¿qué tan fuerte fue el golpe?) y la <strong>dirección</strong> (¿hacia qué lado nos caímos?).</p>
<section id="magnitud-mae-vs.-rmse-lineal-o-exponencial" class="level3">
<h3 class="anchored" data-anchor-id="magnitud-mae-vs.-rmse-lineal-o-exponencial">4.2.1 Magnitud: MAE vs.&nbsp;RMSE (¿Lineal o Exponencial?)</h3>
<p>Estas métricas miden la distancia absoluta entre el plan y la realidad. No les importa el signo, sino el impacto físico del desvío.</p>
<p><strong>A. MAE (Mean Absolute Error): La métrica de la bodega</strong></p>
<p>Es el promedio simple de los errores.</p>
<ul>
<li><p><strong>Interpretación:</strong> Es la “distancia promedio” en unidades.</p></li>
<li><p><strong>Sentido de negocio:</strong> Si el MAE es 50, significa que, en promedio, cada mes te equivocas por 50 cajas. Es ideal para dimensionar capacidad de almacenamiento o mano de obra. <span class="math display">\[
\large MAE = \frac{1}{n} \sum_{i=1}^{n} |Actual_i - Forecast_i|
\]</span></p></li>
</ul>
<p><strong>B. RMSE (Root Mean Square Error): El detector de crisis</strong></p>
<p>Eleva los errores al cuadrado antes de promediar, lo que penaliza severamente los desvíos grandes.</p>
<ul>
<li><p><strong>Interpretación:</strong> Es una medida de variabilidad del error.</p></li>
<li><p><strong>Sentido de negocio:</strong> Un RMSE alto comparado con el MAE indica que tienes “bombazos” (outliers) que están destruyendo tu operación esporádicamente. <span class="math display">\[
\large RMSE = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (Actual_i - Forecast_i)^2}
\]</span></p></li>
</ul>
<p><strong>Variables:</strong> * <span class="math inline">\(Actual_i\)</span>: Demanda real corregida del periodo <span class="math inline">\(i\)</span> (Cap. 2). * <span class="math inline">\(Forecast_i\)</span>: Tu apuesta para ese periodo (Naive o plan oficial). * <span class="math inline">\(\large n\)</span>: Número de periodos evaluados (ventana de error).</p>
<section id="ejemplo-el-efecto-de-los-errores-grandes" class="level4">
<h4 class="anchored" data-anchor-id="ejemplo-el-efecto-de-los-errores-grandes">Ejemplo: El efecto de los errores grandes</h4>
<p>Imagina dos productos con el mismo error total acumulado en 3 meses, pero diferente distribución:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 36%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Mes</th>
<th style="text-align: center;">Producto A (Error Estable)</th>
<th style="text-align: center;">Producto B (Con Outlier)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;"><strong>26</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Total Error Abs.</strong></td>
<td style="text-align: center;"><strong>30</strong></td>
<td style="text-align: center;"><strong>30</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>MAE</strong></td>
<td style="text-align: center;"><strong>10</strong></td>
<td style="text-align: center;"><strong>10</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>RMSE</strong></td>
<td style="text-align: center;"><strong>10</strong></td>
<td style="text-align: center;"><strong>15.1</strong></td>
</tr>
</tbody>
</table>
<p><strong>Lección:</strong> El MAE dice que ambos son igual de “malos”. El RMSE del Producto B es un 50% más alto, alertándote de que el mes 3 fue una catástrofe logística (posible quiebre de stock o flete aéreo de emergencia).</p>
</section>
</section>
<section id="dirección-el-bias-sesgo-o-la-inclinación-al-error" class="level3">
<h3 class="anchored" data-anchor-id="dirección-el-bias-sesgo-o-la-inclinación-al-error">4.2.2 Dirección: El BIAS (Sesgo o la inclinación al error)</h3>
<p>El sesgo es el “error sistémico”. Nos dice si el proceso de planificación está contaminado por optimismo o pesimismo.</p>
<p><span class="math display">\[
\large BIAS = \sum_{i=1}^{n} (Forecast_i - Actual_i)
\]</span></p>
<ul>
<li><p><strong>BIAS Positivo (+):</strong> Estás pronosticando sistemáticamente por encima de la demanda. Resultado: Inventario muerto y capital atrapado.</p></li>
<li><p><strong>BIAS Negativo (-):</strong> Estás pronosticando por debajo. Resultado: Ventas perdidas, clientes enojados y urgencias en producción.</p></li>
</ul>
</section>
<section id="matriz-de-decisión-qué-métrica-usar-y-cuándo" class="level3">
<h3 class="anchored" data-anchor-id="matriz-de-decisión-qué-métrica-usar-y-cuándo">4.2.3 Matriz de Decisión: ¿Qué métrica usar y cuándo?</h3>
<p>Para pulir tu reporte, usa esta guía de fortalezas y debilidades:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Métrica</th>
<th style="text-align: center;">Cuándo es FUERTE</th>
<th style="text-align: center;">Cuándo es FLOJA</th>
<th style="text-align: center;">Recomendación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>MAE</strong></td>
<td style="text-align: center;">Cuando el costo del error es lineal (1 caja extra cuesta siempre lo mismo).</td>
<td style="text-align: center;">Cuando necesitas detectar fallos críticos o muy grandes.</td>
<td style="text-align: center;">Úsala para reportar a <strong>Operaciones</strong> (volumen).</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>RMSE</strong></td>
<td style="text-align: center;">Cuando un error grande es catastrófico (ej. productos perecederos o piezas críticas).</td>
<td style="text-align: center;">Es difícil de explicar a alguien no técnico (¿qué es una “unidad al cuadrado”?).</td>
<td style="text-align: center;">Úsala para <strong>Optimizar Modelos</strong> matemáticos.</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>BIAS</strong></td>
<td style="text-align: center;">Para detectar “vicios” en el equipo comercial o ajustes manuales excesivos.</td>
<td style="text-align: center;">Puede ser engañoso: un BIAS de 0 puede esconder errores gigantes que se cancelan.</td>
<td style="text-align: center;">Úsala para el <strong>S&amp;OP</strong> y corregir el comportamiento.</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Regla de Oro
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Nunca midas solo la magnitud.</strong> Un MAE bajo con un BIAS muy alto significa que estás “fallando poco” pero siempre hacia el mismo lado, lo cual es mucho más fácil de corregir que un error aleatorio. El BIAS es la métrica de la <strong>calidad del proceso</strong>.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="la-batalla-de-las-métricas-mae-bias-vs.-mape" class="level2">
<h2 class="anchored" data-anchor-id="la-batalla-de-las-métricas-mae-bias-vs.-mape">4.3 La Batalla de las Métricas: MAE + BIAS vs.&nbsp;MAPE</h2>
<p>En los pasillos corporativos, el <strong>MAPE (Mean Absolute Percentage Error)</strong> es el rey. Es seductor porque es intuitivo: <em>“Tenemos un error del 10%”</em> suena mucho más claro que <em>“Fallamos por 452 unidades”</em>. Sin embargo, en el mundo de la alta ingeniería de Supply Chain, el MAPE es considerado un “espejismo peligroso”.</p>
<section id="la-maldición-del-porcentaje-por-qué-el-mape-es-tramposo" class="level3">
<h3 class="anchored" data-anchor-id="la-maldición-del-porcentaje-por-qué-el-mape-es-tramposo">4.3.1 La Maldición del Porcentaje: ¿Por qué el MAPE es tramposo?</h3>
<p>El MAPE divide el error entre la demanda real para obtener un porcentaje. Esta operación matemática tan simple esconde tres trampas que pueden arruinar tu estrategia de inventarios:</p>
<ol type="1">
<li><p><strong>El Sesgo de Subestimación (Asimetría):</strong> El MAPE castiga más el exceso de stock que el quiebre. Si pides de más, el error puede ser del 1000%. Si pides de menos, el error nunca superará el 100%. Un algoritmo que intente minimizar el MAPE aprenderá que es “mejor” dejarte sin producto que arriesgarse a que sobre.</p></li>
<li><p><strong>La Explosión del Cero:</strong> Si un producto no tiene ventas en un mes (<span class="math inline">\(y_t=0\)</span>), la fórmula intenta dividir por cero y el sistema colapsa. Esto lo hace inútil para productos de baja rotación (Lumpy/Intermittent).</p></li>
<li><p><strong>Indiferencia de Escala:</strong> El MAPE trata igual un error del 20% en un tornillo de 1 dólar que un 20% en un motor de 10,000 dólares. No tiene visión financiera.</p></li>
</ol>
</section>
<section id="el-experimento-del-espejismo-cómo-el-mape-destruye-tus-ventas" class="level3">
<h3 class="anchored" data-anchor-id="el-experimento-del-espejismo-cómo-el-mape-destruye-tus-ventas">4.3.2 El Experimento del Espejismo: Cómo el MAPE destruye tus ventas</h3>
<p>Imagina que eres el responsable de inventarios y tienes que elegir entre dos escenarios de pronóstico para un producto cuya demanda real fue de <strong>100 unidades</strong>. El impacto en unidades es el mismo (fallaste por 90), pero mira lo que dice el MAPE:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Escenario</th>
<th style="text-align: center;">Demanda Real (<span class="math inline">\(\large y_t\)</span>)</th>
<th style="text-align: center;">Pronóstico (<span class="math inline">\(\large \hat{y}_t\)</span>)</th>
<th style="text-align: center;">Error Absoluto (<span class="math inline">\(MAE\)</span>)</th>
<th style="text-align: center;"><strong>MAPE (%)</strong></th>
<th style="text-align: center;">Consecuencia Operativa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>A: Optimista</strong></td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">190</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;"><strong>90%</strong></td>
<td style="text-align: center;">Te sobra stock.(Costo de almacenamiento)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>B: Pesimista</strong></td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;"><strong>90%</strong></td>
<td style="text-align: center;"><strong>Quiebre de stock.</strong>(Venta perdida y cliente enojado).</td>
</tr>
</tbody>
</table>
<p><strong>Aquí viene la trampa:</strong> Si la demanda real hubiera sido de solo 10 unidades en el Escenario A, el MAPE saltaría a <strong>900%</strong>.</p>
<p><strong>Conclusión:</strong> Para el MAPE, el Escenario B (quedarse sin nada) siempre se verá “menos peor” que el Escenario A. Si optimizas tu empresa basándote solo en MAPE, <strong>estarás diseñando una máquina de quiebres de stock.</strong></p>
</section>
<section id="cuadro-comparativo-en-qué-bando-estás" class="level3">
<h3 class="anchored" data-anchor-id="cuadro-comparativo-en-qué-bando-estás">4.3.3 Cuadro Comparativo: ¿En qué bando estás?</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Característica</th>
<th style="text-align: center;">MAPE (%)</th>
<th style="text-align: center;">MAE + BIAS (Unidades)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Fortaleza Principal</strong></td>
<td style="text-align: center;">Excelente para comunicar a perfiles no técnicos.</td>
<td style="text-align: center;">Refleja la realidad física de la bodega.</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Punto Débil</strong></td>
<td style="text-align: center;">Induce al desabasto sistemático.</td>
<td style="text-align: center;">Difícil de comparar entre productos de distinta escala.</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Manejo de Ceros</strong></td>
<td style="text-align: center;">Inservible (Div/0).</td>
<td style="text-align: center;">Robusto y confiable.</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Uso Ideal</strong></td>
<td style="text-align: center;">Reportes ejecutivos de muy alto nivel.</td>
<td style="text-align: center;">Operación diaria, compras y planificación.</td>
</tr>
</tbody>
</table>
</section>
<section id="el-traductor-corporativo-a-quién-le-cuento-qué" class="level3">
<h3 class="anchored" data-anchor-id="el-traductor-corporativo-a-quién-le-cuento-qué">4.3.4 El “Traductor Corporativo”: ¿A quién le cuento qué?</h3>
<p>No todas las métricas son para todos los oídos. Para ser un líder efectivo, debes adaptar el mensaje:</p>
<ul>
<li><p><strong>Para el CEO / Gerente General:</strong> Usa el <strong>WAPE</strong> (ver sección 4.4). Es un porcentaje, pero sin las trampas del MAPE. Les da la sensación de escala que buscan.</p></li>
<li><p><strong>Para el CFO / Finanzas:</strong> Traduce el <strong>MAE a Dinero</strong>. <em>“Nuestro error equivale a $50,000 USD de capital en riesgo mensualmente”</em>. Esto consigue presupuestos para mejores herramientas.</p></li>
<li><p><strong>Para el Jefe de Almacén / Operaciones:</strong> Háblales en <strong>MAE de Unidades</strong>. <em>“Prepárate para mover 1,200 unidades extra de margen de error”</em>.</p></li>
<li><p><strong>Para el Director de S&amp;OP:</strong> Usa el <strong>BIAS</strong>. Es la única métrica que les dirá si el equipo comercial está inflando las proyecciones para “asegurar bono” o si producción está siendo demasiado conservadora.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Recomendación Master
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si te obligan a usar MAPE, acompáñalo siempre del <strong>BIAS</strong>. Si el MAPE es del 15% pero el BIAS es de -12%, ya sabes que ese 15% de error se está convirtiendo casi totalmente en ventas perdidas.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="el-wape-weighted-mape-el-estándar-de-oro-para-gerencia" class="level2">
<h2 class="anchored" data-anchor-id="el-wape-weighted-mape-el-estándar-de-oro-para-gerencia">4.4 El WAPE (Weighted MAPE): El Estándar de Oro para Gerencia</h2>
<p>Si el MAE es para la bodega y el MAPE es un espejismo, el <strong>WAPE (Weighted Mean Absolute Percentage Error)</strong> es la métrica que pone a todos de acuerdo. Es el “Traductor Universal” de la Supply Chain.</p>
<p>El WAPE resuelve el mayor pecado del MAPE: tratar a todos los productos por igual. En lugar de promediar porcentajes individuales, el WAPE suma todos los errores y los divide entre la demanda total del portafolio.</p>
<p><span class="math display">\[
\large WAPE = \frac{\sum |Actual_i - Forecast_i|}{\sum Actual_i}
\]</span></p>
<section id="por-qué-es-el-puente-estratégico" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-es-el-puente-estratégico">4.4.1 ¿Por qué es el puente estratégico?</h3>
<ol type="1">
<li><p><strong>Ponderación Automática:</strong> Le da más peso a lo que más vende. Un error de 1,000 unidades en un producto Clase A impactará el WAPE mucho más que ese mismo error en un producto Clase C.</p></li>
<li><p><strong>Inmunidad al Cero:</strong> Como la suma de la demanda total de la empresa casi nunca es cero, la fórmula es estable y no explota.</p></li>
<li><p><strong>Visión de Portafolio:</strong> Permite decir “Nuestra operación tiene un 15% de error” con total rigor matemático, ya que ese 15% representa el volumen real que se desvió del plan.</p></li>
</ol>
</section>
<section id="ejemplo-el-wape-en-acción-portafolio-a-vs.-b" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-el-wape-en-acción-portafolio-a-vs.-b">4.4.2 Ejemplo: El WAPE en acción (Portafolio A vs.&nbsp;B)</h3>
<p>Imagina una empresa que vende dos productos. Uno es una estrella de ventas y el otro es un accesorio marginal.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Producto</th>
<th style="text-align: center;">Demanda Real</th>
<th style="text-align: center;">Pronóstico</th>
<th style="text-align: center;">Error Abs.</th>
<th style="text-align: center;">MAPE (Indiv.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>A (Best Seller)</strong></td>
<td style="text-align: center;">1,000</td>
<td style="text-align: center;">900</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">10%</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>B (Accesorio)</strong></td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">90%</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Totales</strong></td>
<td style="text-align: center;"><strong>1,010</strong></td>
<td style="text-align: center;"><strong>901</strong></td>
<td style="text-align: center;"><strong>109</strong></td>
<td style="text-align: center;"><strong>Promedio: 50%</strong></td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>El diagnóstico del MAPE (50%):</strong> ¡Alarma roja! El gerente pensará que la mitad de la empresa está mal planificada.</p></li>
<li><p><strong>El diagnóstico del WAPE:</strong> <span class="math inline">\(\large\frac{109}{1,010} = \mathbf{10.8\%}\)</span>.</p></li>
</ul>
<p><strong>La realidad profesional:</strong> La operación está bastante sana (10.8% de error real sobre el volumen total). El MAPE nos estaba mintiendo al darle la misma importancia al accesorio que al best seller. El WAPE pone las cosas en su lugar.</p>
</section>
<section id="fortalezas-y-debilidades-del-wape" class="level3">
<h3 class="anchored" data-anchor-id="fortalezas-y-debilidades-del-wape">4.4.3 Fortalezas y Debilidades del WAPE</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Característica</th>
<th style="text-align: center;">WAPE (Weighted MAPE)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Cuándo es FUERTE</strong></td>
<td style="text-align: center;">Para reportar desempeño mensual a la Dirección General. Para comparar la precisión entre diferentes regiones o categorías de productos.</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Cuándo es FLOJO</strong></td>
<td style="text-align: center;">Si el portafolio tiene precios muy disparatados (un error en una joya de oro pesa igual que un error en un clavo si solo miras unidades).</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Recomendación</strong></td>
<td style="text-align: center;">Si tus productos tienen precios muy distintos, usa el <strong>WAPE en Valor Dinero</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="resumen-de-selección-qué-métrica-elijo" class="level3">
<h3 class="anchored" data-anchor-id="resumen-de-selección-qué-métrica-elijo">4.4.4 Resumen de Selección: ¿Qué métrica elijo?</h3>
<p>Para cerrar tu reporte de métricas, sigue esta jerarquía:</p>
<ol type="1">
<li><p><strong>¿Quieres optimizar el modelo matemático?</strong> Usa <strong>RMSE</strong>.</p></li>
<li><p><strong>¿Quieres planificar la capacidad de la bodega?</strong> Usa <strong>MAE</strong>.</p></li>
<li><p><strong>¿Quieres saber si tu equipo está siendo muy optimista?</strong> Usa <strong>BIAS</strong>.</p></li>
<li><p><strong>¿Quieres presentar resultados a la Junta Directiva?</strong> Usa <strong>WAPE</strong>.</p></li>
<li><p><strong>¿Quieres vivir en un espejismo peligroso?</strong> Usa solo el <strong>MAPE</strong> (y prepárate para los quiebres de stock inesperados).</p></li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>El WAPE no es el fin del camino
</div>
</div>
<div class="callout-body-container callout-body">
<p>Aunque el WAPE es excelente para reportar, recuerda que “oculta” los errores individuales. Un WAPE del 10% puede esconder un producto crítico que está quebrado al 100%. Por eso, el analista senior mira el <strong>WAPE para el bosque</strong> y el <strong>MAE/BIAS para los árboles</strong>.</p>
</div>
</div>
</section>
</section>
<section id="forecastability-el-límite-de-lo-posible" class="level2">
<h2 class="anchored" data-anchor-id="forecastability-el-límite-de-lo-posible">4.5 Forecastability: El Límite de lo Posible</h2>
<p>En Supply Chain, hay una verdad incómoda: <strong>No todo se puede predecir.</strong> Exigir un WAPE del 5% a un producto con demanda errática es como intentar predecir el resultado de un dado; no es un problema de falta de inteligencia, sino de la naturaleza del fenómeno. La <strong>Forecastability(Pronosticalidad)</strong> es la medida de qué tan “predecible” es un producto basándose en su estabilidad histórica.</p>
<section id="el-coeficiente-de-variación-cv-tu-detector-de-ruido" class="level3">
<h3 class="anchored" data-anchor-id="el-coeficiente-de-variación-cv-tu-detector-de-ruido">4.5.1 El Coeficiente de Variación (CV): Tu detector de ruido</h3>
<p>Para medir la predecibilidad, usamos el <strong>Coeficiente de Variación (CV)</strong>. Es una métrica simple que compara la desviación estándar con el promedio.</p>
<p><span class="math display">\[
\large CV = \frac{\sigma}{\mu} = \frac{\text{Desviación Estándar}}{\text{Promedio}}
\]</span></p>
<ul>
<li><p><strong>CV Bajo (&lt; 0.5):</strong> Demanda “suave” (Smooth). Es el sueño de cualquier planificador. Los errores aquí suelen ser responsabilidad del modelo o del proceso humano.</p></li>
<li><p><strong>CV Alto (&gt; 1.0):</strong> Demanda “caótica” o “errática” (Lumpy). Aquí, el error es inherente al azar. No importa qué tan avanzado sea tu algoritmo, siempre habrá un margen de error alto.</p></li>
</ul>
</section>
<section id="la-matriz-de-predecibilidad" class="level3">
<h3 class="anchored" data-anchor-id="la-matriz-de-predecibilidad">4.5.2 La Matriz de Predecibilidad</h3>
<p>No midas a todos con la misma vara. Clasifica tus productos en este cuadrante para gestionar las expectativas de la gerencia:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 38%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Tipo de Demanda</th>
<th style="text-align: center;">Comportamiento</th>
<th style="text-align: center;">Estrategia de Pronóstico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Estable (Smooth)</strong></td>
<td style="text-align: center;">Ventas constantes, bajas fluctuaciones.</td>
<td style="text-align: center;">Modelos estadísticos clásicos (Suavizamiento, ARIMA). El objetivo es <strong>Precisión Máxima</strong>.</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Intermitente</strong></td>
<td style="text-align: center;">Muchos meses con venta cero y picos repentinos.</td>
<td style="text-align: center;">Modelos de Croston o SBA. El objetivo es <strong>Nivel de Servicio</strong>, no precisión.</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Errática (Lumpy)</strong></td>
<td style="text-align: center;">Volumen alto pero con cambios violentos.</td>
<td style="text-align: center;">Inteligencia de Mercado y Colaboración (S&amp;OP). El algoritmo solo dará una base.</td>
</tr>
</tbody>
</table>
</section>
<section id="por-qué-importa-esto-el-impacto-en-el-stock-de-seguridad" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-importa-esto-el-impacto-en-el-stock-de-seguridad">4.5.3 ¿Por qué importa esto? El impacto en el Stock de Seguridad</h3>
<p>La predecibilidad dicta tu costo financiero. Existe una relación directa entre el <strong>CV</strong> y el <strong>Stock de Seguridad</strong>:</p>
<ul>
<li><p>A mayor CV (más ruido), necesitas más inventario de protección para evitar el quiebre.</p></li>
<li><p>Si intentas “forzar” un pronóstico preciso en un producto de CV alto, solo lograrás que el sistema de compras reaccione de forma histérica (efecto látigo), pidiendo demasiado hoy y nada mañana.</p></li>
</ul>
</section>
<section id="el-escudo-del-planificador-concepto-de-forecast-goal" class="level3">
<h3 class="anchored" data-anchor-id="el-escudo-del-planificador-concepto-de-forecast-goal">4.5.4 El Escudo del Planificador (Concepto de “Forecast Goal”)</h3>
<p>Un error común en las empresas es poner una meta única de precisión (ej. “Queremos un 80% de Accuracy global”). Esto es un error estratégico. Un líder de Supply Chain maduro establece metas diferenciadas:</p>
<ul>
<li><p><strong>Productos Clase A / Estables:</strong> Meta 85% Accuracy.</p></li>
<li><p><strong>Productos Clase B / Erráticos:</strong> Meta 60% Accuracy.</p></li>
<li><p><strong>Nuevos lanzamientos:</strong> Meta 40% Accuracy.</p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Antes de aceptar un KPI de error, calcula el CV de tu portafolio. Si el 70% de tus SKU tienen un CV &gt; 1.0, un error (WAPE) del 30% no es un mal desempeño; es, probablemente, el límite de lo que la estadística puede alcanzar. <strong>Usa el CV para defender la integridad de tu trabajo.</strong></p>
</div>
</div>
</section>
</section>
<section id="tracking-signal-la-alarma-de-incendio-del-pronosticador" class="level2">
<h2 class="anchored" data-anchor-id="tracking-signal-la-alarma-de-incendio-del-pronosticador">4.6 Tracking Signal: La Alarma de Incendio del Pronosticador</h2>
<p>Hasta ahora hemos medido fotos fijas: el error de este mes o el promedio del trimestre. Pero el error es dinámico. El <strong>Tracking Signal (TS)</strong> es una métrica de control de calidad que nos avisa, en tiempo real, si nuestro modelo de pronóstico ha dejado de ser válido porque la demanda cambió de patrón (cambio estructural).</p>
<p>Es, en esencia, un termómetro que detecta si el <strong>BIAS</strong> (sesgo) se está acumulando de forma peligrosa hacia un lado.</p>
<section id="cómo-se-calcula" class="level3">
<h3 class="anchored" data-anchor-id="cómo-se-calcula">4.6.1 ¿Cómo se calcula?</h3>
<p>El Tracking Signal compara la suma acumulada de los errores con la magnitud promedio del error (MAD o MAE).</p>
<p><span class="math display">\[
\large TS = \frac{\sum (Actual_i - Forecast_i)}{MAD}
\]</span></p>
<p>Donde el <strong>MAD (Mean Absolute Deviation)</strong> es simplemente el MAE calculado de forma rodante.</p>
</section>
<section id="interpretación-los-límites-de-control" class="level3">
<h3 class="anchored" data-anchor-id="interpretación-los-límites-de-control">4.6.2 Interpretación: Los Límites de Control</h3>
<p>Imagina que estás conduciendo un auto. El Tracking Signal es el indicador que te dice si te estás saliendo del carril:</p>
<ul>
<li><p><strong>TS = 0:</strong> El modelo es perfecto. Los errores positivos se cancelan exactamente con los negativos.</p></li>
<li><p><strong>Límites Ideales (</strong><span class="math inline">\(\pm4\)</span><strong>):</strong> En la industria, se considera que si el TS se mantiene entre <strong>-4 y 4</strong>, el error es puramente aleatorio (ruido blanco). Estás dentro del carril.</p></li>
<li><p><strong>TS &gt; 4:</strong> Estás subestimando la demanda de forma sistemática. Te vas a quedar sin stock pronto. El modelo “se quedó corto”.</p></li>
<li><p><strong>TS &lt; -4:</strong> Estás sobreestimando. Estás llenando la bodega de inventario que no se mueve. El modelo “se pasó de largo”.</p></li>
</ul>
</section>
<section id="el-tablero-de-control-visualizando-el-desvío" class="level3">
<h3 class="anchored" data-anchor-id="el-tablero-de-control-visualizando-el-desvío">4.6.3 El Tablero de Control: Visualizando el Desvío</h3>
<p>No esperes a fin de mes para revisar el WAPE. Un analista Pro tiene un gráfico de control donde el TS se ve así:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Mes</th>
<th style="text-align: center;">Error Real</th>
<th style="text-align: center;">Suma Error Acum.</th>
<th style="text-align: center;">MAD (MAE)</th>
<th style="text-align: center;"><strong>Tracking Signal</strong></th>
<th style="text-align: center;">Estado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">+10</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">OK</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">+15</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">12.5</td>
<td style="text-align: center;">2.0</td>
<td style="text-align: center;">OK</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">+20</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;"><strong>3.0</strong></td>
<td style="text-align: center;">Alerta Amarilla</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">+25</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">17.5</td>
<td style="text-align: center;"><strong>4.0</strong></td>
<td style="text-align: center;"><strong>¡ALARMA!</strong></td>
</tr>
</tbody>
</table>
<p><strong>Diagnóstico:</strong> Aunque el error individual no parece gigante, el hecho de que sea <strong>siempre positivo</strong> hace que el TS trepe rápidamente. En el mes 4, el sistema te grita: <em>“¡Deja de usar este modelo, algo cambió en el mercado!”</em>.</p>
</section>
<section id="qué-hacer-cuando-suena-la-alarma" class="level3">
<h3 class="anchored" data-anchor-id="qué-hacer-cuando-suena-la-alarma">4.6.4 ¿Qué hacer cuando suena la alarma?</h3>
<p>Cuando un producto “dispara” el Tracking Signal, no sirve de nada ajustar el número a mano. Debes investigar la causa raíz:</p>
<ol type="1">
<li><p><strong>Cambio de Tendencia:</strong> ¿Entró un competidor nuevo? ¿Hubo una campaña de marketing no comunicada?</p></li>
<li><p><strong>Obsolescencia del Modelo:</strong> ¿Estamos usando un promedio móvil para un producto que ahora tiene estacionalidad?</p></li>
<li><p><strong>Promociones:</strong> ¿Hubo un “push” de ventas que rompió la historia?</p></li>
</ol>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Error del Principiante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Muchos analistas ven un error grande y corren a cambiar el pronóstico. El analista Senior mira el <strong>Tracking Signal</strong>. Si el error es grande pero el TS está cerca de cero, es un evento fortuito (ruido). <strong>No toques nada.</strong> Si el error es pequeño pero el TS es 4.5, tienes un problema sistémico. <strong>Actúa de inmediato.</strong></p>
</div>
</div>
<hr>
</section>
</section>
<section id="el-laboratorio-de-diagnóstico-implementación-en-r" class="level2">
<h2 class="anchored" data-anchor-id="el-laboratorio-de-diagnóstico-implementación-en-r">4.7 El Laboratorio de Diagnóstico: Implementación en R</h2>
<p>De nada sirve la teoría si no puedes ejecutarla sobre tus datos. En esta sección, construiremos un script profesional que automatiza el cálculo de todas las métricas vistas y genera un tablero de control para detectar anomalías.</p>
<section id="el-script-de-auditoría-de-pronósticos" class="level3">
<h3 class="anchored" data-anchor-id="el-script-de-auditoría-de-pronósticos">4.7.1 El Script de Auditoría de Pronósticos</h3>
<p>Este script utiliza el ecosistema <code>tidyverse</code> para procesar los datos y calcular el <strong>FVA (Forecast Value Added)</strong>, que nos dirá si nuestro proceso humano está mejorando o empeorando el pronóstico básico (Naive).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargamos las librerías silenciando los mensajes de inicio</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(scales)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(patchwork)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Creación del Modelo de Simulación (datos_auditoria)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulamos 12 meses con una tendencia alcista donde el forecast se queda atrás</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>datos_auditoria <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">mes =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">demanda_real =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">115</span>, <span class="dv">110</span>, <span class="dv">125</span>, <span class="dv">140</span>, <span class="dv">135</span>, <span class="dv">150</span>, <span class="dv">165</span>, <span class="dv">160</span>, <span class="dv">175</span>, <span class="dv">190</span>, <span class="dv">195</span>),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">forecast_comercial =</span> <span class="fu">c</span>(<span class="dv">95</span>, <span class="dv">100</span>, <span class="dv">105</span>, <span class="dv">110</span>, <span class="dv">120</span>, <span class="dv">125</span>, <span class="dv">130</span>, <span class="dv">140</span>, <span class="dv">150</span>, <span class="dv">155</span>, <span class="dv">165</span>, <span class="dv">175</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">error_abs_comercial =</span> <span class="fu">abs</span>(demanda_real <span class="sc">-</span> forecast_comercial),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">bias_comercial =</span> forecast_comercial <span class="sc">-</span> demanda_real,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">bias_acumulado =</span> <span class="fu">cumsum</span>(bias_comercial),</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">mad_rodante =</span> <span class="fu">cummean</span>(error_abs_comercial),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">tracking_signal =</span> bias_acumulado <span class="sc">/</span> mad_rodante</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Gráfico 1: Comparativa Demanda vs. Pronóstico</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos_auditoria, <span class="fu">aes</span>(<span class="at">x =</span> mes)) <span class="sc">+</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> demanda_real, <span class="at">color =</span> <span class="st">"Demanda Real"</span>), <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> forecast_comercial, <span class="at">color =</span> <span class="st">"Forecast Comercial"</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> demanda_real, <span class="at">color =</span> <span class="st">"Demanda Real"</span>), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Auditoría de Desempeño: Demanda vs. Pronóstico"</span>,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Análisis de precisión del plan comercial"</span>,</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Unidades"</span>,</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Mes"</span>,</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Referencia"</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Demanda Real"</span> <span class="ot">=</span> <span class="st">"#2c3e50"</span>, <span class="st">"Forecast Comercial"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>)) <span class="sc">+</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Gráfico 2: Tracking Signal (Límites de Control)</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos_auditoria, <span class="fu">aes</span>(<span class="at">x =</span> mes, <span class="at">y =</span> tracking_signal)) <span class="sc">+</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">fill =</span> <span class="st">"#3498db"</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#2980b9"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#2980b9"</span>) <span class="sc">+</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"#c0392b"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fl">4.5</span>, <span class="at">label =</span> <span class="st">"Límite Superior (Sobre-pronóstico)"</span>, <span class="at">color =</span> <span class="st">"#c0392b"</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="sc">-</span><span class="fl">4.5</span>, <span class="at">label =</span> <span class="st">"Límite Inferior (Sub-pronóstico)"</span>, <span class="at">color =</span> <span class="st">"#c0392b"</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Monitoreo de Tracking Signal"</span>,</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Detección de sesgo sistemático (Límites ±4)"</span>,</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"TS (Ratio)"</span>,</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Mes"</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Usamos coord_cartesian para hacer zoom sin eliminar datos fuera de rango</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">7</span>, <span class="dv">7</span>)) <span class="sc">+</span> </span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Combinación de Gráficos (Patchwork)</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">/</span> p2 <span class="sc">+</span> <span class="fu">plot_annotation</span>(</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Panel de Diagnóstico de Supply Chain"</span>,</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>  <span class="at">theme =</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cap-4-metricas-error_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La interpretación de este panel se divide en dos niveles: el <strong>desempeño inmediato</strong> (arriba) y la <strong>salud del proceso</strong> (abajo).</p>
<p>Aquí tienes la guía para leer lo que el script acaba de generar:</p>
</section>
<section id="gráfico-superior-auditoría-de-desempeño-el-qué" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-superior-auditoría-de-desempeño-el-qué">1. Gráfico Superior: Auditoría de Desempeño (El “Qué”)</h3>
<p>Este gráfico muestra la “foto” mes a mes.</p>
<ul>
<li><p><strong>La Brecha (Gap):</strong> Observa que la línea roja (Forecast) está casi siempre por debajo de la azul (Demanda). Esto te dice de inmediato que el equipo comercial está siendo <strong>conservador o pesimista</strong>.</p></li>
<li><p><strong>La Reacción:</strong> Nota cómo la línea roja intenta “perseguir” a la azul pero siempre llega tarde. Esto se conoce como un <strong>pronóstico rezagado</strong>, típico de cuando solo se mira el pasado reciente sin entender la tendencia alcista.</p></li>
</ul>
</section>
<section id="gráfico-inferior-tracking-signal-el-por-qué" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-inferior-tracking-signal-el-por-qué">2. Gráfico Inferior: Tracking Signal (El “Por qué”)</h3>
<p>Este es el gráfico más importante para un analista senior, porque mide el <strong>sesgo sistemático</strong>.</p>
<ul>
<li><p><strong>La Dirección (Pendiente):</strong> La línea azul cae de forma constante. En la fórmula del Tracking Signal, cuando el resultado es <strong>negativo</strong>, significa que la demanda real está superando al pronóstico.</p></li>
<li><p><strong>Los Límites Críticos (</strong><span class="math inline">\(\pm 4\)</span>):</p>
<ul>
<li><p><strong>Zona Blanca (entre -4 y 4):</strong> El error se considera “ruido” aceptable o aleatorio. El modelo está “dentro del carril”.</p></li>
<li><p><strong>Zona Roja (fuera de</strong> <span class="math inline">\(\pm 4\)</span>): En tu gráfica, la línea cruza el <strong>-4</strong> alrededor del mes 6 o 7. <strong>Aquí es donde suena la alarma.</strong> El modelo ya no es confiable; no es un error de un solo mes, es un error de diseño. El proceso está “roto”.</p></li>
</ul></li>
</ul>
</section>
<section id="diagnóstico-final-del-modelo-simulado" class="level3">
<h3 class="anchored" data-anchor-id="diagnóstico-final-del-modelo-simulado">3. Diagnóstico Final del Modelo Simulado</h3>
<p>Si este fuera tu negocio real, la conclusión sería:</p>
<blockquote class="blockquote">
<p><em>“Tenemos un <strong>sesgo de sub-pronóstico sistemático</strong>. El equipo comercial está ignorando el crecimiento del mercado. Esto no se arregla ‘ajustando un poquito’ el próximo mes; necesitamos cambiar el algoritmo por uno que capture mejor la tendencia, porque el Tracking Signal nos indica que estamos fuera de control estadístico desde hace 5 meses.”</em></p>
</blockquote>
</section>
<section id="resumen-para-gerencia" class="level3">
<h3 class="anchored" data-anchor-id="resumen-para-gerencia">Resumen para Gerencia:</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Si la línea del Tracking Signal…</strong></td>
<td><strong>Significa que…</strong></td>
<td><strong>Riesgo para el negocio</strong></td>
</tr>
<tr class="even">
<td><strong>Sube y cruza el +4</strong></td>
<td>Pronosticamos de más (Optimismo).</td>
<td>Exceso de inventario y capital atrapado.</td>
</tr>
<tr class="odd">
<td><strong>Baja y cruza el -4</strong></td>
<td>Pronosticamos de menos (Pesimismo).</td>
<td><strong>Quiebres de stock y ventas perdidas.</strong></td>
</tr>
<tr class="even">
<td><strong>Zigzaguea cerca de 0</strong></td>
<td>El error es aleatorio.</td>
<td>Proceso sano y bajo control.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="conclusión-del-espejo-retrovisor-al-parabrisas" class="level2">
<h2 class="anchored" data-anchor-id="conclusión-del-espejo-retrovisor-al-parabrisas">4.8 Conclusión: Del Espejo Retrovisor al Parabrisas</h2>
<p>Hemos llegado al final de la <strong>Parte I: Los Cimientos</strong>. Si has seguido este recorrido, has pasado de la intuición al rigor técnico. Muchas empresas intentan saltar directamente a la Inteligencia Artificial sin haber pasado por estos cuatro pasos, y ese es el motivo por el cual el 80% de los proyectos de analítica en Supply Chain fracasan.</p>
<section id="el-recuento-de-los-daños-y-de-las-ganancias" class="level3">
<h3 class="anchored" data-anchor-id="el-recuento-de-los-daños-y-de-las-ganancias">4.8.1 El Recuento de los Daños (y de las Ganancias)</h3>
<p>Hagamos un inventario de lo que ahora tienes en tu arsenal:</p>
<ol type="1">
<li><p><strong>Datos Auditados (Cap. 1):</strong> Ya no confías ciegamente en el ERP. Sabes dónde están las trampas de los datos.</p></li>
<li><p><strong>Demanda Real (Cap. 2):</strong> Dejaste de planificar sobre “ventas” y empezaste a planificar sobre “necesidades del mercado”, limpiando el ruido de las promociones y los quiebres.</p></li>
<li><p><strong>Segmentación Estratégica (Cap. 3):</strong> Sabes que no todos los SKU nacieron iguales. Tienes un mapa ABC-XYZ que dicta dónde poner tu tiempo y tu dinero.</p></li>
<li><p><strong>Métricas de Verdad (Cap. 4):</strong> Tienes un <strong>Baseline</strong> (Naive) y un sistema de alarmas (Tracking Signal). Ya nadie puede engañarte con un “vamos bien” basado en un MAPE mentiroso.</p></li>
</ol>
</section>
<section id="la-transición-de-lo-descriptivo-a-lo-predictivo" class="level3">
<h3 class="anchored" data-anchor-id="la-transición-de-lo-descriptivo-a-lo-predictivo">4.8.2 La Transición: De lo Descriptivo a lo Predictivo</h3>
<p>Hasta este momento, hemos estado mirando el <strong>espejo retrovisor</strong>. Hemos analizado el pasado para entender nuestra posición actual. Pero la Supply Chain no se conduce mirando hacia atrás.</p>
<p>A partir del próximo capítulo, entramos en la <strong>Parte II: El Laboratorio de Pronósticos</strong>. Aquí es donde el bisturí se convierte en motor. Dejaremos de preguntar <em>“¿Qué pasó?”</em> para empezar a resolver la pregunta del millón: <strong>“¿Qué va a pasar mañana?”</strong>.</p>
</section>
<section id="hoja-de-ruta-lo-que-viene-en-la-parte-ii" class="level3">
<h3 class="anchored" data-anchor-id="hoja-de-ruta-lo-que-viene-en-la-parte-ii">4.8.3 Hoja de Ruta: Lo que viene en la Parte II</h3>
<p>En los siguientes capítulos, convertiremos todo este diagnóstico en planes de acción:</p>
<ul>
<li><p><strong>Modelos Estadísticos:</strong> Desde el suavizamiento exponencial hasta ARIMA.</p></li>
<li><p><strong>Machine Learning:</strong> Cómo usar variables externas (clima, precios, festivos) para anticiparnos al mercado.</p></li>
<li><p><strong>S&amp;OP Proactivo:</strong> Cómo usar tus nuevas métricas para liderar la reunión de ventas y operaciones con datos, no con opiniones.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Tu Próximo Paso
</div>
</div>
<div class="callout-body-container callout-body">
<p>Antes de pasar al Capítulo 5, asegúrate de tener calculado el <strong>WAPE y el BIAS de los últimos 6 meses</strong> de tu portafolio actual. Ese será el “muro” contra el que lanzaremos nuestros nuevos modelos para ver si realmente somos capaces de mejorar la realidad.</p>
<p><strong>Si no puedes medir la mejora, la mejora no existe.</strong></p>
</div>
</div>
<p><em>Hemos terminado la fase de preparación. La infraestructura está lista. Es hora de empezar a predecir.</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./cap-3-abcxyz-dinamico.html" class="pagination-link" aria-label="3. Clasificando el Caos: Segmentación ABC/XYZ Dinámica">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">3. Clasificando el Caos: Segmentación ABC/XYZ Dinámica</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./cap-5-pronostico-ingenuo.html" class="pagination-link" aria-label="5. El Pronóstico Ingenuo: Modelos Simples y Benchmarking">
        <span class="nav-page-text"><span class="chapter-title">5. El Pronóstico Ingenuo: Modelos Simples y Benchmarking</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Nicolás A. Bravo</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/nicobravo933-Planner/nicobravo933-Planner/edit/main/cap-4-metricas-error.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/nicobravo933-Planner/nicobravo933-Planner/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Este libro fue creado con <a href="https://quarto.org/">Quarto</a>. Visita mi <a href="https://github.com/nicobravo933-Planner">repositorio GitHub</a>.</p>
</div>
  </div>
</footer>




</body></html>